In [3]:
import pandas as pd

In [4]:
df_train_house_prices = pd.read_csv('/home/shashank/workspace/datascience/assignment/datavisualization/house-prices-advanced-regression-techniques/train.csv')
df_test_house_prices = pd.read_csv('/home/shashank/workspace/datascience/assignment/datavisualization/house-prices-advanced-regression-techniques/train.csv')

df_train_titanic_prices = pd.read_csv('/home/shashank/workspace/datascience/assignment/datavisualization/data_visualization/titanic/train.csv')
df_test_titanic_prices = pd.read_csv('/home/shashank/workspace/datascience/assignment/datavisualization/data_visualization/titanic/test.csv')

In [5]:
# OBTAINING COLUMN WISE NAN ELEMENT COUNT AND PERCENTAGE

# We'll consider that when more than 15% of the data is missing, we should delete the 
# corresponding variable and pretend it never existed. 
# This means that we will not try any trick to fill the missing data in these cases.

df_train=df_train_house_prices.copy(deep=True)
len(df_train) # it returns total number of rows in a dataframe 
total = df_train.isnull().sum().sort_values(ascending=False) # it gives column wise total NAN elements (series type)
total_nan =df_train.isnull().sum().sum() # it gives total NAN elements in all columns (series type)
df_train.count() # it gives count of non null element in a column (columnwise) (series type)
df_train.isnull().count() # it gives count of total elements(including null element) in a column (columnwise) (series type)
df_train.sum() # it add up all element in a column (if object type then element get concatenated) (series type)
df_train.isnull().count().sum() #  it gives count of total elements(including null element) in entire dataframe
df_train.count().sum() #  it gives count of total elements(excluding null element) in entire dataframe
percent = (df_train.isnull().sum()/df_train.isnull().count()).sort_values(ascending=False)

missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent']) # it returns dataframe  

missing_data.head(20)

              Total   Percent
PoolQC         1453  0.995205
MiscFeature    1406  0.963014
Alley          1369  0.937671
Fence          1179  0.807534
FireplaceQu     690  0.472603
LotFrontage     259  0.177397
GarageCond       81  0.055479
GarageType       81  0.055479
GarageYrBlt      81  0.055479
GarageFinish     81  0.055479
GarageQual       81  0.055479
BsmtExposure     38  0.026027
BsmtFinType2     38  0.026027
BsmtFinType1     37  0.025342
BsmtCond         37  0.025342
BsmtQual         37  0.025342
MasVnrArea        8  0.005479
MasVnrType        8  0.005479
Electrical        1  0.000685
Utilities         0  0.000000

In [6]:
# OBTAINING PERCENTAGE OF NAN ELEMENTS IN A DATAFRAME
print(df_train.isnull().sum().sum())
print(df_train.isnull().count().sum())

p=(float(df_train.isnull().sum().sum())/float(df_train.isnull().count().sum()))*100
p

6965
118260

5.889565364451209

In [12]:
# Method of renaming a column in a dataframe

ms=missing_data.rename(columns={0:"Total_New",1:"Percentage_New"})

In [18]:
# this method gives me the number of column of various datatype 
df_train.dtypes.value_counts()

object     43
int64      35
float64     3
dtype: int64

In [19]:
# this method gives us a dataframe containing object type column 
df_train.select_dtypes('object')

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [20]:
# apply a method on dataframe which returns a series containing column name annd count of unique element in that column.
df_train.select_dtypes('object').apply(pd.Series.nunique, axis = 0)

MSZoning          5
Street            2
Alley             2
LotShape          4
LandContour       4
Utilities         2
LotConfig         5
LandSlope         3
Neighborhood     25
Condition1        9
Condition2        8
BldgType          5
HouseStyle        8
RoofStyle         6
RoofMatl          8
Exterior1st      15
Exterior2nd      16
MasVnrType        4
ExterQual         4
ExterCond         5
Foundation        6
BsmtQual          4
BsmtCond          4
BsmtExposure      4
BsmtFinType1      6
BsmtFinType2      6
Heating           6
HeatingQC         5
CentralAir        2
Electrical        5
KitchenQual       4
Functional        7
FireplaceQu       5
GarageType        6
GarageFinish      3
GarageQual        5
GarageCond        5
PavedDrive        3
PoolQC            3
Fence             4
MiscFeature       4
SaleType          9
SaleCondition     6
dtype: int64

## Demerit of label encoding
Before we go any further, we need to deal with pesky categorical variables. A machine learning model unfortunately cannot deal with categorical variables (except for some models such as LightGBM). Therefore, we have to find a way to encode (represent) these variables as numbers before handing them off to the model. There are two main ways to carry out this process:

Label encoding: assign each unique category in a categorical variable with an integer. No new columns are created. An example is shown below
image

One-hot encoding: create a new column for each unique category in a categorical variable. Each observation recieves a 1 in the column for its corresponding category and a 0 in all other new columns.
image

The problem with label encoding is that it gives the categories an arbitrary ordering. The value assigned to each of the categories is random and does not reflect any inherent aspect of the category. In the example above, programmer recieves a 4 and data scientist a 1, but if we did the same process again, the labels could be reversed or completely different. The actual assignment of the integers is arbitrary. Therefore, when we perform label encoding, the model might use the relative value of the feature (for example programmer = 4 and data scientist = 1) to assign weights which is not what we want. If we only have two unique values for a categorical variable (such as Male/Female), then label encoding is fine, but for more than 2 unique categories, one-hot encoding is the safe option.

## Demerit of one hot encoding 
downside to one-hot encoding is that the number of features (dimensions of the data) can explode with categorical variables with many categories. To deal with this, we can perform one-hot encoding followed by PCA or other dimensionality reduction methods to reduce the number of dimensions (while still trying to preserve information).

# Next Step in EDA is Handeling Anamolies
One problem we always want to be on the lookout for when doing EDA is anomalies within the data. These may be due to mis-typed numbers, errors in measuring equipment, or they could be valid but extreme measurements.


One way to support anomalies quantitatively is by looking at the statistics of a column using the describe method.

# Next Step in EDA is Handeling Anamolies

## Correlations

Now that we have dealt with the categorical variables and the outliers, let's continue with the EDA. One way to try and understand the data is by looking for correlations between the features and the target. We can calculate the Pearson correlation coefficient between every variable and the target using the .corr dataframe method.

In [ ]:
# Find correlations with the target and sort
#correlations = app_train.corr()['TARGET'].sort_values()